version: "2"

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2.1
    # Enables the web UI and tells Traefik to listen to docker
    # command: --configFile=/home/ec2-user/sphinx-deploy/traefik.yaml
    command:
      - "--log.level=DEBUG"
    ports:
      # The HTTP port
      - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
      # entrypoints
      - 443:443
      - 5000:5000
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik.yaml:/etc/traefik/traefik.yaml
      - ./docker/letsencrypt:/letsencrypt
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
    logging:
      options:
        max-size: 10m
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  # auth:
  #   image: sphinx-auth
  #   depends_on:
  #     - reverse-proxy
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.auth.rule=Host(`auth.sphinx.chat`)"
  #     - "traefik.http.services.auth.loadbalancer.server.port=9090"
  #     - "traefik.http.routers.auth.tls=true"
  #     - "traefik.http.routers.auth.tls.certresolver=myresolver"
  #     - "traefik.http.routers.auth.entrypoints=websecure"
  #   restart: on-failure
  #   environment:
  #     - JWT_KEY=$JWT_KEY
  #     - CLIENT_KEYS=$CLIENT_KEYS
  #     - OAUTH_TIMEOUT=$OAUTH_TIMEOUT

  memes:
    build: .
    depends_on:
      # - auth
      - reverse-proxy
    labels:
      - "traefik.enable=true"

      # web : insecure
      - "traefik.http.routers.tribes.rule=Host(`$HOST`)"
      - "traefik.http.services.tribes.loadbalancer.server.port=$PORT"
      - "traefik.http.routers.tribes.entrypoints=web"

      # # web : secure
      # - "traefik.http.routers.tribes.rule=Host(`$HOST`)"
      # - "traefik.http.services.tribes.loadbalancer.server.port=$PORT"
      # - "traefik.http.routers.tribes.tls=true"
      # - "traefik.http.routers.tribes.tls.certresolver=myresolver"
      # - "traefik.http.routers.tribes.entrypoints=websecure"

    restart: on-failure
    environment:
      - HOST=$HOST
      - STORAGE_MODE=$STORAGE_MODE
      - S3_KEY=$S3_KEY
      - S3_SECRET=$S3_SECRET
      - S3_BUCKET=$S3_BUCKET
      - RDS_HOSTNAME=$RDS_HOSTNAME
      - RDS_PORT=$RDS_PORT
      - RDS_DB_NAME=$RDS_DB_NAME
      - RDS_USERNAME=$RDS_USERNAME
      - RDS_PASSWORD=$RDS_PASSWORD
      - JWT_KEY=$JWT_KEY
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000
